### ISSUE TITLE
Buat migration dan seeder untuk data yang mau divisualisasikan

### ISSUE THREAD

**Issue by ekoptra** [ihkaru/nisputviz#1]
Tabelnya nanti bernama `irio_summary` dengn jumlah 8 kolom yaitu
- kode_prov
- provinsi
- kode_kategori
- kategori
- latitude
- longitude
- variable
- value

**Comment by ihkaru** [comment]
Okeis, nnti yg buat migrationnya kamu ko? atau aku?

**Comment by ekoptra** [comment]
Aku Za, itu ada di `Assignees`
